data:
    dataset: "CT"
    category: ""
    image_size: 256
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    complex_abs: false
    ct_norm: true
    num_workers: 0
    out_of_dist: false

model:
    type: "simple"
    in_channels: 1
    out_ch: 1
    ch: 64
    ch_mult: [1, 2, 4, 4, 8, 16]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
