data:
    dataset: "MRI"
    category: ""
    image_size: [640, 368]
    channels: 2
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    complex_abs: true
    ct_norm: false
    num_workers: 0
    out_of_dist: false
    vertical_mask: true
    L30: false
    L2: true

model:
    type: "simple"
    in_channels: 2
    out_ch: 2
    ch: 64
    ch_mult: [1, 1, 2, 4, 8]
    num_res_blocks: 2
    attn_resolutions: [23]
    dropout: 0.1
    var_type: fixedsmall
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
